/**
 * ! Document Object Model (DOM) is used to manipulate the element in HTML, is generated by the navigator, and javascript use it to give dynamism in the page. 
 */
// ? To select an element like in CSS
var box = document.querySelector('#box');
console.log("This is an element", box);

// * change the style with JS
box.style.width = "200px";
box.style.height = "200px";
box.style.background = "black";

// ? To select elements like in CSS by class
var boxes = document.querySelectorAll(".boxes");
console.log("These are elements", boxes);